{
 "title": "Rhino",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "TTF value",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "TFF",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "ttf",
     "select": [
      [
       { "params": [ "ttf" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=", "value": "ESP58:7A:82 " }
     ]
    }
   ]
  },
  {
   "title": "Voltage ESP58:7A",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Voltage [V]" }
   ],
   "targets": [
    {
     "alias": "AVG",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "current",
     "select": [
      [
       { "params": [ "avgVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=", "value": "ESP58:7A:82 " }
     ]
    },
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "current",
     "select": [
      [
       { "params": [ "maxVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=", "value": "ESP58:7A:82 " }
     ]
    },
    {
     "alias": "Min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "current",
     "select": [
      [
       { "params": [ "minVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=", "value": "ESP58:7A:82 " }
     ]
    },
    {
     "alias": "Std",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "current",
     "select": [
      [
       { "params": [ "stdVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=", "value": "ESP58:7A:82 " }
     ]
    }
   ]
  },
  {
   "title": "Notification for different strings",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "wdt():",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "specificstring",
     "select": [
      [
       { "params": [ "serial" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=", "value": "ESP58:7A:82 " },
      { "condition": "AND", "key": "notificationString", "operator": "=", "value": "wdt():" }
     ]
    },
    {
     "alias": "gps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "specificstring",
     "select": [
      [
       { "params": [ "serial" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=", "value": "ESP58:7A:82 " },
      { "condition": "AND", "key": "notificationString", "operator": "=", "value": "gps" }
     ]
    }
   ]
  },
  {
   "title": "Current consumption ESP58:7A",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Current [mA]" }
   ],
   "targets": [
    {
     "alias": "AVG",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "current",
     "select": [
      [
       { "params": [ "avgCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=", "value": "ESP58:7A:82 " }
     ]
    },
    {
     "alias": "MAX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "current",
     "select": [
      [
       { "params": [ "maxCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=", "value": "ESP58:7A:82 " }
     ]
    },
    {
     "alias": "MIN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "current",
     "select": [
      [
       { "params": [ "minCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=", "value": "ESP58:7A:82 " }
     ]
    },
    {
     "alias": "STD",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "current",
     "select": [
      [
       { "params": [ "stdCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=", "value": "ESP58:7A:82 " }
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "measurement": "serial",
     "select": [
      [
       { "params": [ "serial" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceId", "operator": "=", "value": "ESP58:7A:82 " }
     ]
    }
   ]
  }
 ]
}